spring:
  application:
    name: SEOgenix

  data:
    mongodb:
      uri: ${MONGO_URI}
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      connect-timeout: 60000

  openAI:
    key: ${OPEN_ROUTER_KEY}